# Generated by Django 6.0 on 2026-02-09 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_systemaccesspermission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32')], max_length=4, verbose_name='Subnet')),
                ('name', models.CharField(max_length=50, verbose_name='نام محدوده')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('vlan', models.IntegerField(blank=True, null=True, verbose_name='Vlan')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس MAC')),
                ('os', models.CharField(blank=True, max_length=500, null=True, verbose_name='سیستم عامل')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name='تولیدکننده')),
                ('category', models.CharField(blank=True, choices=[('data-and-information', 'داده و اطلاعات'), ('software', 'نرم افزار'), ('services', 'سرویس'), ('hardware', 'سخت افزار'), ('places-and-areas', 'اماکن و محوطه'), ('human-resource', 'منابع انسانی'), ('infrastructure-asset', 'دارایی های زیر ساخت'), ('intangible-asset', 'دارایی های نامشهود'), ('supplier', 'تامین کنندگان')], default='بدون دسته بندی', max_length=250, null=True, verbose_name='دسته دارایی')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان شناسایی')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('network_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicovered_aasets', to='ip_management.ipmanage', verbose_name='محدوده شبکه')),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'در حال اجرا'), ('finished', 'تکمیل شده'), ('failed', 'ناموفق'), ('no_new_ip', 'ip جدیدی یافت نشد'), ('canceled', 'کنسل شده')], default='running', max_length=20, verbose_name='وضعیت')),
                ('result_count', models.IntegerField(default=0, verbose_name='تعداد یافته\u200cها')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('network_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='ip_management.ipmanage', verbose_name='محدوده شبکه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
