# Generated by Django 6.0 on 2025-12-29 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32')], max_length=4, verbose_name='ساب\u200cنت (Subnet)')),
                ('name', models.CharField(max_length=50, verbose_name='نام محدوده')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('vlan', models.IntegerField(blank=True, null=True, verbose_name='وی\u200cلن (VLAN)')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس MAC')),
                ('os', models.CharField(blank=True, max_length=500, null=True, verbose_name='سیستم عامل')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name='تولیدکننده')),
                ('category', models.CharField(blank=True, choices=[('0', 'داده و اطلاعات'), ('1', 'نرم افزار'), ('2', 'سرویس'), ('3', 'سخت افزار'), ('4', 'اماکن و محوطه'), ('5', 'منابع انسانی'), ('6', 'دارایی های زیر ساخت'), ('7', 'دارایی های نامشهود'), ('8', 'تامین کنندگان')], default='بدون دسته بندی', max_length=250, null=True, verbose_name='دسته دارایی')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان شناسایی')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('network_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicovered_aasets', to='ip_management.ipmanage', verbose_name='محدوده شبکه')),
            ],
        ),
    ]
