# Generated by Django 6.0 on 2026-01-17 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'در حال اجرا'), ('finished', 'تکمیل شده'), ('failied', 'ناموفق')], default='running', max_length=20, verbose_name='وضعیت')),
                ('result_count', models.IntegerField(default=0, verbose_name='تعداد یافته\u200cها')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('finished_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ پایان')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('network_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='ip_management.ipmanage', verbose_name='محدوده شبکه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
