# Generated by Django 6.0 on 2026-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0004_alter_discoveredasset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('finished', 'تکمیل شده'), ('failed', 'ناموفق')], default='running', max_length=20, verbose_name='وضعیت'),
        ),
    ]
