# Generated by Django 6.0 on 2026-01-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0005_alter_scanhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('finished', 'تکمیل شده'), ('failed', 'ناموفق'), ('no_new_ip', 'No new IP found')], default='running', max_length=20, verbose_name='وضعیت'),
        ),
    ]
