# Generated by Django 6.0 on 2026-02-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0006_alter_scanhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredasset',
            name='category',
            field=models.CharField(blank=True, choices=[('data-and-information', 'داده و اطلاعات'), ('software', 'نرم افزار'), ('services', 'سرویس'), ('hardware', 'سخت افزار'), ('places-and-areas', 'اماکن و محوطه'), ('human-resource', 'منابع انسانی'), ('infrastructure-asset', 'دارایی های زیر ساخت'), ('intangible-asset', 'دارایی های نامشهود'), ('supplier', 'تامین کنندگان')], default='', max_length=250, null=True, verbose_name='دسته دارایی'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('finished', 'تکمیل شده'), ('failed', 'ناموفق'), ('no_new_ip', 'ip جدیدی یافت نشد'), ('canceled', 'کنسل شده')], default='running', max_length=20, verbose_name='وضعیت'),
        ),
    ]
