# Generated by Django 6.0 on 2026-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0007_alter_discoveredasset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredasset',
            name='category',
            field=models.CharField(blank=True, choices=[('data-and-information', 'داده و اطلاعات'), ('software', 'نرم افزار'), ('services', 'سرویس'), ('hardware', 'سخت افزار'), ('places-and-areas', 'اماکن و محوطه'), ('human-resource', 'منابع انسانی'), ('infrastructure-asset', 'دارایی های زیر ساخت'), ('intangible-asset', 'دارایی های نامشهود'), ('supplier', 'تامین کنندگان')], default='بدون دسته بندی', max_length=250, null=True, verbose_name='دسته دارایی'),
        ),
    ]
