# Generated by Django 6.0 on 2026-02-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0008_alter_discoveredasset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID'),
        ),
    ]
