# Generated by Django 6.0 on 2026-02-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0009_scanhistory_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='finished_at',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
    ]
