# Generated by Django 6.0 on 2026-02-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_management', '0010_alter_scanhistory_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
    ]
