# Generated by Django 6.0 on 2026-02-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemaccesspermission_options'),
        ('ip_management', '0011_alter_scanhistory_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ipmanage',
            name='subnet',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32')], max_length=4, verbose_name='Subnet'),
        ),
        migrations.AlterField(
            model_name='ipmanage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='ipmanage',
            name='vlan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vlan'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر'),
        ),
    ]
