# Generated by Django 6.0 on 2025-12-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('places_and_areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesandarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization', verbose_name='سازمان'),
        ),
        migrations.AlterField(
            model_name='placesandarea',
            name='sub_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.suborganization', verbose_name='زیرمجموعه'),
        ),
    ]
