# Generated by Django 6.0 on 2026-01-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='license_expired_date',
            new_name='license_expired_date',
        ),
    ]
