# Generated by Django 6.0 on 2026-02-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemaccesspermission_options'),
        ('software', '0003_rename_license_expired_data_software_license_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر'),
        ),
    ]
