# Generated by Django 6.0 on 2025-12-29 07:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ip_manage_crud', 'مدیریت کامل رکوردهای IP (ایجاد، مشاهده، ویرایش، حذف)'), ('ip_manage_r', 'فقط مشاهده رکوردهای IP'), ('data_and_information_crud', 'مدیریت کامل داده\u200cها و اطلاعات'), ('data_and_information_r', 'فقط مشاهده داده\u200cها و اطلاعات'), ('software_crud', 'مدیریت کامل نرم\u200cافزارها'), ('software_r', 'فقط مشاهده نرم\u200cافزارها'), ('services_crud', 'مدیریت کامل سرویس\u200cها'), ('services_r', 'فقط مشاهده سرویس\u200cها'), ('hardware_crud', 'مدیریت کامل سخت\u200cافزارها'), ('hardware_r', 'فقط مشاهده سخت\u200cافزارها'), ('place_and_areas_crud', 'مدیریت کامل اماکن و محوطه\u200cها'), ('place_and_areas_r', 'فقط مشاهده اماکن و محوطه\u200cها'), ('human_resources_crud', 'مدیریت کامل منابع انسانی'), ('human_resources_r', 'فقط مشاهده منابع انسانی'), ('infrastructure_crud', 'مدیریت کامل زیرساخت\u200cها'), ('infrastructure_r', 'فقط مشاهده زیرساخت\u200cها'), ('intangible_assets_crud', 'مدیریت کامل دارایی\u200cهای نامشهود'), ('intangible_assets_r', 'فقط مشاهده دارایی\u200cهای نامشهود'), ('suppliers_crud', 'مدیریت کامل تامین\u200cکنندگان'), ('suppliers_r', 'فقط مشاهده تامین\u200cکنندگان'), ('can_response_to_tickets', 'امکان پاسخگویی به تیکت\u200cها'), ('can_manage_helpdesk_setting', 'مدیریت تنظیمات هلپ\u200cدسک'), ('can_use_scanners', 'امکان استفاده از اسکنرهای دارایی'), ('can_answer_questions', 'امکان پاسخ به سوالات کاربران')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Active_directory_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=50, verbose_name='آدرس سرور (IP/Domain)')),
                ('domain_name', models.CharField(max_length=50, verbose_name='نام دامنه (Domain Name)')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری اتصال')),
                ('password', models.CharField(max_length=50, verbose_name='رمز عبور اتصال')),
                ('port', models.IntegerField(verbose_name='پورت اتصال')),
                ('search_base', models.CharField(max_length=50, verbose_name='پایه جستجو (Search Base)')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, verbose_name='نام سطح')),
                ('main_level', models.BooleanField(default=False, verbose_name='سطح اصلی است؟')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accesslevel', verbose_name='سطح بالادستی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=255, null=True, verbose_name='جنسیت')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='آخرین ویرایش پروفایل')),
                ('last_login', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('ip_login', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید (OTP)')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تایید')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='گروه\u200cها')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='مجوزهای کاربر')),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.accesslevel', verbose_name='سطح دسترسی')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
