# Generated by Django 6.0 on 2025-12-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaccesspermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ip_manage_crud', 'مدیریت کامل رکوردهای IP (ایجاد، مشاهده، ویرایش، حذف)'), ('ip_manage_r', 'فقط مشاهده رکوردهای IP'), ('data_and_information_crud', 'مدیریت کامل داده\u200cها و اطلاعات'), ('data_and_information_r', 'فقط مشاهده داده\u200cها و اطلاعات'), ('software_crud', 'مدیریت کامل نرم\u200cافزارها'), ('software_r', 'فقط مشاهده نرم\u200cافزارها'), ('services_crud', 'مدیریت کامل سرویس\u200cها'), ('services_r', 'فقط مشاهده سرویس\u200cها'), ('hardware_crud', 'مدیریت کامل سخت\u200cافزارها'), ('hardware_r', 'فقط مشاهده سخت\u200cافزارها'), ('place_and_areas_crud', 'مدیریت کامل اماکن و محوطه\u200cها'), ('place_and_areas_r', 'فقط مشاهده اماکن و محوطه\u200cها'), ('human_resources_crud', 'مدیریت کامل منابع انسانی'), ('human_resources_r', 'فقط مشاهده منابع انسانی'), ('infrastructure_assets_crud', 'مدیریت کامل زیرساخت\u200cها'), ('infrastructure_assets_r', 'فقط مشاهده زیرساخت\u200cها'), ('intangible_assets_crud', 'مدیریت کامل دارایی\u200cهای نامشهود'), ('intangible_assets_r', 'فقط مشاهده دارایی\u200cهای نامشهود'), ('suppliers_crud', 'مدیریت کامل تامین\u200cکنندگان'), ('suppliers_r', 'فقط مشاهده تامین\u200cکنندگان'), ('can_response_to_tickets', 'امکان پاسخگویی به تیکت\u200cها'), ('can_manage_helpdesk_setting', 'مدیریت تنظیمات هلپ\u200cدسک'), ('can_use_scanners', 'امکان استفاده از اسکنرهای دارایی'), ('can_answer_questions', 'امکان پاسخ به سوالات کاربران')]},
        ),
    ]
