# Generated by Django 6.0 on 2025-12-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_systemaccesspermission_options'),
        ('active_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_directory_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='active_directory.activedirectory', verbose_name='سرور اکتیو دایرکتوری مرجع'),
        ),
    ]
