# Generated by Django 6.0 on 2025-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_directory_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requirement_to_change_the_password',
            field=models.BooleanField(default=False, verbose_name='اجبار برای تغییر رمز عبور'),
        ),
    ]
