# Generated by Django 6.0 on 2026-02-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requirement_to_change_the_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaccesspermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('asset_ip_manage_crud', 'مدیریت کامل رکوردهای IP (ایجاد، مشاهده، ویرایش، حذف)'), ('asset_ip_manage_r', 'فقط مشاهده رکوردهای IP'), ('asset_data_and_information_crud', 'مدیریت کامل داده\u200cها و اطلاعات'), ('asset_data_and_information_r', 'فقط مشاهده داده\u200cها و اطلاعات'), ('asset_software_crud', 'مدیریت کامل نرم\u200cافزارها'), ('asset_software_r', 'فقط مشاهده نرم\u200cافزارها'), ('asset_services_crud', 'مدیریت کامل سرویس\u200cها'), ('asset_services_r', 'فقط مشاهده سرویس\u200cها'), ('asset_hardware_crud', 'مدیریت کامل سخت\u200cافزارها'), ('asset_hardware_r', 'فقط مشاهده سخت\u200cافزارها'), ('asset_place_and_areas_crud', 'مدیریت کامل اماکن و محوطه\u200cها'), ('asset_place_and_areas_r', 'فقط مشاهده اماکن و محوطه\u200cها'), ('asset_human_resources_crud', 'مدیریت کامل منابع انسانی'), ('asset_human_resources_r', 'فقط مشاهده منابع انسانی'), ('asset_infrastructure_assets_crud', 'مدیریت کامل زیرساخت\u200cها'), ('asset_infrastructure_assets_r', 'فقط مشاهده زیرساخت\u200cها'), ('asset_intangible_assets_crud', 'مدیریت کامل دارایی\u200cهای نامشهود'), ('asset_intangible_assets_r', 'فقط مشاهده دارایی\u200cهای نامشهود'), ('asset_suppliers_crud', 'مدیریت کامل تامین\u200cکنندگان'), ('asset_suppliers_r', 'فقط مشاهده تامین\u200cکنندگان'), ('can_response_to_tickets', 'امکان پاسخگویی به تیکت\u200cها'), ('can_manage_helpdesk_setting', 'مدیریت تنظیمات هلپ\u200cدسک'), ('can_use_scanners', 'امکان استفاده از اسکنرهای دارایی'), ('can_answer_questions', 'امکان پاسخ به سوالات کاربران')]},
        ),
    ]
