# Generated by Django 6.0 on 2026-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemaccesspermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requirement_to_change_the_password',
            field=models.BooleanField(default=True, verbose_name='اجبار برای تغییر رمز عبور'),
        ),
    ]
