# Generated by Django 6.0 on 2026-02-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_requirement_to_change_the_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='requirement_to_change_the_password',
            new_name='is_requirement_to_change_the_password',
        ),
    ]
