# Generated by Django 6.0 on 2025-12-29 07:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس IP')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس MAC')),
                ('os', models.CharField(blank=True, max_length=500, null=True, verbose_name='سیستم عامل')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name='تولیدکننده (Vendor)')),
                ('network_id', models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='شناسه شبکه')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('supplier', models.CharField(blank=True, max_length=500, null=True, verbose_name='تامین\u200cکننده/پشتیبان')),
                ('hardening', models.CharField(blank=True, max_length=500, null=True, verbose_name='وضعیت امن\u200cسازی')),
                ('vulner_status', models.CharField(blank=True, max_length=500, null=True, verbose_name='وضعیت آسیب\u200cپذیری')),
                ('status', models.CharField(blank=True, max_length=500, null=True, verbose_name='وضعیت عملیاتی')),
                ('hostname', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام میزبان')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='شماره پورت')),
                ('model', models.CharField(blank=True, max_length=500, null=True, verbose_name='مدل دستگاه')),
                ('manufacturer', models.CharField(blank=True, max_length=500, null=True, verbose_name='سازنده/برند')),
                ('hardware_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع سخت\u200cافزار')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام سخت افزار')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='سازمان')),
                ('sub_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.suborganization', verbose_name='زیرمجموعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
