# Generated by Django 6.0 on 2025-12-29 07:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس IP')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس MAC')),
                ('os', models.CharField(blank=True, max_length=500, null=True, verbose_name='سیستم عامل')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name='تولیدکننده (Vendor)')),
                ('network_id', models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='شناسه شبکه')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام و نام خانوادگی')),
                ('manager', models.CharField(blank=True, max_length=500, null=True, verbose_name='مدیر مستقیم')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع به کار')),
                ('end_date_of_work', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری')),
                ('organizational_unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='واحد سازمانی')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='محل استقرار / دفتر')),
                ('administrative_position', models.CharField(blank=True, max_length=500, null=True, verbose_name='پست سازمانی / سمت')),
                ('personnel_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره پرسنلی')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='سازمان')),
                ('sub_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.suborganization', verbose_name='زیرمجموعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
