# Generated by Django 6.0 on 2025-12-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('website', models.CharField(blank=True, max_length=500, null=True, verbose_name='وب\u200cسایت')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واحد/زیرمجموعه')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس اختصاصی')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='سازمان بالادستی')),
            ],
        ),
    ]
