# Generated by Django 6.0 on 2025-12-30 09:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='suborganization',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
    ]
