# Generated by Django 6.0 on 2025-12-29 07:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_category', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='متن سوال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info_summary', models.CharField(max_length=255, verbose_name='اطلاعات کاربر (IP یا نام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='اتاق فعال است؟')),
                ('requires_password_reset', models.BooleanField(default=False, verbose_name='درخواست رمز عبور')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('priority', models.CharField(choices=[('0', 'کم اهمیت'), ('1', 'معمولی'), ('2', 'ویژه')], default='1', max_length=1, verbose_name='اولویت')),
                ('related_asset_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی دارایی مرتبط')),
                ('related_asset_category', models.CharField(blank=True, choices=[('0', 'بدون دسته\u200cبندی'), ('1', 'داده\u200cها و اطلاعات'), ('2', 'نرم\u200cافزار'), ('3', 'سرویس'), ('4', 'سخت\u200cافزار'), ('5', 'اماکن و محوطه'), ('6', 'منابع انسانی'), ('7', 'دارایی\u200cهای زیرساختی'), ('8', 'دارایی\u200cهای نامشهود'), ('9', 'تامین\u200cکنندگان')], max_length=2, null=True, verbose_name='گروه دارایی مرتبط')),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.messagecategory', verbose_name='دسته بندی پیام')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.question', verbose_name='موضوع سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('seen_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان مشاهده')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='خوانده شده توسط')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticketroom', verbose_name='اتاق تیکت')),
            ],
        ),
    ]
