# Generated by Django 6.0 on 2026-02-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_requirement_to_change_the_password_user_is_requirement_to_change_the_password'),
        ('ticket', '0002_alter_messagecategory_user_alter_question_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accesslevel', verbose_name='سطح دسترسی'),
        ),
    ]
