# Generated by Django 6.0 on 2026-02-23 07:41

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_requirement_to_change_the_password_user_is_requirement_to_change_the_password'),
        ('ticket', '0003_question_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_category', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AlterField(
            model_name='ticketroom',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticketcategory', verbose_name='دسته بندی پیام'),
        ),
        migrations.DeleteModel(
            name='MessageCategory',
        ),
    ]
