# Generated by Django 6.0 on 2025-12-29 07:31

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAndInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس IP')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس MAC')),
                ('os', models.CharField(blank=True, max_length=500, null=True, verbose_name='سیستم عامل')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name='تولیدکننده (Vendor)')),
                ('network_id', models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='شناسه شبکه')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('location', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='محل نگهداری')),
                ('usage', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='مورد مصرف')),
                ('owner', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='مالک')),
                ('confidentiality_level', models.CharField(blank=True, choices=[('0', 'خصوصی'), ('1', 'محرمانه'), ('2', 'عمومی')], default='-', max_length=400, null=True, verbose_name='سطح محرمانگی')),
                ('version', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='نسخه')),
                ('document_type', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='نوع مسنتد')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='سازمان')),
                ('sub_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.suborganization', verbose_name='زیرمجموعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
