# Generated by Django 6.0 on 2026-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_and_information', '0002_alter_dataandinformation_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataandinformation',
            name='confidentiality_level',
            field=models.CharField(blank=True, choices=[('0', 'خصوصی'), ('1', 'محرمانه'), ('2', 'عمومی')], max_length=400, null=True, verbose_name='سطح محرمانگی'),
        ),
        migrations.AlterField(
            model_name='dataandinformation',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع مسنتد'),
        ),
        migrations.AlterField(
            model_name='dataandinformation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محل نگهداری'),
        ),
        migrations.AlterField(
            model_name='dataandinformation',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='dataandinformation',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مورد مصرف'),
        ),
        migrations.AlterField(
            model_name='dataandinformation',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسخه'),
        ),
    ]
