# Generated by Django 6.0 on 2025-12-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('data_and_information', '0002_alter_dataandinformation_organization_and_more'),
        ('hardware', '0002_alter_hardware_organization_and_more'),
        ('human_resources', '0002_alter_humanresource_organization_and_more'),
        ('infrastructure_assets', '0002_alter_infrastructureassets_organization_and_more'),
        ('intangible_assets', '0002_alter_intangibleasset_organization_and_more'),
        ('places_and_areas', '0002_alter_placesandarea_organization_and_more'),
        ('services', '0002_alter_services_organization_and_more'),
        ('software', '0002_alter_software_organization_and_more'),
        ('supplier', '0002_alter_supplier_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborganization',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='SubOrganization',
        ),
    ]
