# Generated by Django 6.0 on 2025-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=50, verbose_name='آدرس سرور')),
                ('domain_name', models.CharField(max_length=50, verbose_name='نام دامنه')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=50, verbose_name='رمز عبور')),
                ('port', models.IntegerField(verbose_name='پورت')),
                ('search_base', models.CharField(max_length=50, verbose_name='پایه جستجو (Search Base)')),
            ],
        ),
    ]
