# Generated by Django 6.0 on 2025-12-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectory',
            name='search_base',
            field=models.CharField(max_length=250, verbose_name='پایه جستجو (Search Base)'),
        ),
    ]
