# Generated by Django 6.0 on 2026-01-20 13:43

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requirement_to_change_the_password'),
        ('active_directory', '0002_alter_activedirectory_search_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedirectory',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActiveDirectoryUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=250, verbose_name='رمز عبور')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('active_directory_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='active_directory.activedirectory', verbose_name='سرور اکتیو دایرکتوری مرجع')),
            ],
        ),
    ]
