# Generated by Django 6.0 on 2026-01-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requirement_to_change_the_password'),
        ('active_directory', '0003_activedirectory_access_level_activedirectoryusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedirectoryusers',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accesslevel', verbose_name='سطح دسترسی'),
            preserve_default=False,
        ),
    ]
