# Generated by Django 6.0 on 2026-02-21 09:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_directory', '0004_activedirectoryusers_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedirectory',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default='2026-2-21', verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
