# Generated by Django 6.0 on 2026-02-21 09:09

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_directory', '0005_activedirectory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectory',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
    ]
