# Generated by Django 6.0 on 2026-02-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemaccesspermission_options'),
        ('intangible_assets', '0002_alter_intangibleasset_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intangibleasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر'),
        ),
    ]
